	DB 'admiral',0h
	DB 'anaconda',0h
	DB 'beekeeper',0h
	DB 'blabbering',0h
	DB 'bummer',0h
	DB 'buzzer',0h
	DB 'difficult',0h
	DB 'dizzy',0h
	DB 'fizzy',0h
	DB 'fuzzy',0h
	DB 'fluffy',0h
	DB 'hound',0h
	DB 'joking',0h
	DB 'joker',0h
	DB 'overjoyed',0h
	DB 'poncho',0h
	DB 'yellow',0h
	DB 'zigzagging',0h
	DB 'sausage',0h
	DB 'blubber',0h
	DB 'pencil',0h
	DB 'cloud',0h
	DB 'moon',0h
	DB 'water',0h
	DB 'computer',0h
	DB 'school',0h
	DB 'network',0h
	DB 'hammer',0h
	DB 'walking',0h
	DB 'mediocre',0h
	DB 'literature',0h
	DB 'chair',0h
	DB 'window',0h
	DB 'cords',0h
	DB 'musical',0h
	DB 'zebra',0h
	DB 'xylophone',0h
	DB 'penguin',0h
	DB 'home',0h
	DB 'hound',0h
	DB 'final',0h
	DB 'inked',0h
	DB 'teacher',0h
	DB 'funny',0h
	DB 'website',0h
	DB 'banana',0h
	DB 'uncle',0h
	DB 'softly',0h
	DB 'awesome',0h
	DB 'attach',0h
	DB 'blue',0h
	DB 'internet',0h
	DB 'bottle',0h
	DB 'tight',0h
	DB 'zone',0h
	DB 'tomato',0h
	DB 'prison',0h
	DB 'hydro',0h
	DB 'cleaning',0h
	DB 'telivision',0h
	DB 'send',0h
	DB 'frog',0h
	DB 'coffee',0h
	DB 'book',0h
	DB 'zooming',0h
	DB 'falling',0h
	DB 'evily',0h
	DB 'gamer',0h
	DB 'juice',0h
	DB 'moniter',0h
	DB 'captain',0h
	DB 'bonding',0h
	DB 'loudly',0h
	DB 'thudding',0h
	DB 'guitar',0h
	DB 'shaving',0h
	DB 'hair',0h
	DB 'soccer',0h
	DB 'water',0h
	DB 'racket',0h
	DB 'table',0h
	DB 'late',0h
	DB 'media',0h
	DB 'desktop',0h
	DB 'flipper',0h
	DB 'club',0h
	DB 'flying',0h
	DB 'smooth',0h
	DB 'monster',0h
	DB 'purple',0h
	DB 'guardian',0h
	DB 'bold',0h
	DB 'hyperlink',0h
	DB 'presenter',0h
	DB 'world',0h
	DB 'national',0h
	DB 'comment',0h
	DB 'element',0h
	DB 'magic',0h
	DB 'lion',0h
	DB 'sand',0h
	DB 'crust',0h
	DB 'toast',0h
	DB 'hunter',0h
	DB 'forest',0h
	DB 'foraging',0h
	DB 'silent',0h
	DB 'pong',0h
	DB 'waves',0h 
	DB 'narwahl',0h 
	DB 'volcano',0h 